spring:
  cloud:
    gateway:
      routes: #配置路由规则
        - id: cactus-workbench-route
          uri: lb://cactus-workbench
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: cactus-auth-route
          uri: lb://cactus-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  redis:
    database: 0
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:cactus-redis}
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:6764/rsa/publicKey

secure:
  ignore:
    urls: #配置白名单路径
      - /actuator/**
      - /auth/oauth/token

logging:
  level:
    org.springframework.cloud.gateway: trace
